[pytest]

addopts = -s
          -v
          #--headed
          --browser chromium
          --html=C:/Users/admin/PycharmProjects/PythonProject/My_New_Project/reports/html-reports/report.html --self-contained-html
          --alluredir=C:/Users/admin/PycharmProjects/PythonProject/My_New_Project/reports/allure-results

--slowmo = 500